[package]
name = "saver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
getopts = "0.2.21"
termdraw = { version = "0.1.0", git = "ssh://git@github.com/oxidecomputer/facade.git" }
facade-terminal = { git = "ssh://git@github.com/oxidecomputer/facade.git" }
